.TH BITCOIN8M-CLI "1" "February 2016" "bitcoin8m-cli 0.12"
.SH NAME
bitcoin8m-cli \- a remote procedure call client for Bitcoin8m Core. 
.SH SYNOPSIS
bitcoin8m-cli [options] <command> [params] \- Send command to Bitcoin8m Core. 
.TP
bitcoin8m-cli [options] help \- Asks Bitcoin8m Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the bitcoin8m-cli program. bitcoin8m-cli is an RPC client used to send commands to Bitcoin8m Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBbitcoin8md\fP, \fBbitcoin8m.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
