.TH BITCOIN8MD "1" "February 2016" "bitcoin8md 0.12"
.SH NAME
bitcoin8md \- peer-to-peer network based digital currency
.SH SYNOPSIS
bitcoin8m [options] <command> [params]  
.TP
bitcoin8m [options] help <command> \- Get help for a command
.SH DESCRIPTION
This  manual page documents the bitcoin8md program. Bitcoin8m is an experimental new digital currency that enables instant payments to anyone, anywhere in the world. Bitcoin8m uses peer-to-peer technology to operate with no central authority: managing transactions and issuing money are carried out collectively by the network. Bitcoin8m Core is the name of open source software which enables the use of this currency.

.SH OPTIONS
.TP
\-?
List of possible options.
.SH COMMANDS
.TP
\fBhelp\fR
List commands.

.TP
\fBhelp 'command'\fR
Get help for a command.

.SH "SEE ALSO"
bitcoin8m.conf(5)
.SH AUTHOR
This manual page was written by Micah Anderson <micah@debian.org> for the Debian system (but may be used by others). Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 or any later version published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.

